### ISSUE TITLE
[BUG]: 长文本越界

### ISSUE THREAD

**Issue by WindRunnerMax** [SHST-SDUST/SHST-PLUS#1]
新鲜事模块存在文本越界问题

<img width="485" alt="image" src="https://github.com/SHST-SDUST/SHST-PLUS/assets/33169019/660cad43-c369-4daf-8f99-ee4380dea30c">

需要加入
```css
.style {
    word-break: break-word;
}
```
